### ISSUE TITLE
How to stop an infinite loop

### ISSUE THREAD

**Issue by carolynsala585** [quarkslab/tritondse#11]
I have a simple target that runs a chatbot, it receives packets from the network and runs in `while(1){}`. In this case, how does tritondse work? How does it stop program execution and do path exploration based on the injected symbolic packet through  `inject_symbolic_variable_memory` function? 

I tried `se.abort()` and `se.stop_exploration()`, but they didn't work for me. Maybe it's something on my end.

I'd appreciate any help and advice.

**Comment by RobinDavid** [comment]
Hi @carolynsala585.
TritonDSE strictly emulates the program, so it can runs indefinitely. However you have few Config parameters that can help:
* ``execution_timeout`` bound the execution time of  1 execution
* ``exploration_timeout`` bound the overall exploration
* ``exploration_limit`` limit the number of iteration (number of ``SymbolicExecutor``)

Otherwise, yes in callbacks you can manually use ``se.abort()`` or ``se.stop_exploration()`` they are meant to do the job. The only problem I see is that your callbacks where they are located are never hit.
